{"level":"error","message":"Error while fetching the todos Database failure","service":"user-service","stack":"Error: Database failure\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:11:05.856Z"}
{"level":"error","message":"Error while fetching the todos Database failure","service":"user-service","stack":"Error: Database failure\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:14:49.274Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:16:30.501Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:45:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:28:41.199Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T14:58:43.954Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T14:59:21.434Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T15:06:31.765Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:76:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T15:06:31.795Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:45:57.226Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:45:57.242Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:48:03.464Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:48:03.484Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:49:24.753Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:49:24.775Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:50:29.285Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:50:29.305Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:51:57.821Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:51:57.845Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:52:32.448Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:52:32.476Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:54:55.888Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:54:55.904Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:57:31.215Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T04:57:31.232Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:03:10.537Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:03:10.555Z"}
{"_message":"Todo validation failed","errors":{"title":{"kind":"required","message":"Path `title` is required.","name":"ValidatorError","path":"title","properties":{"message":"Path `title` is required.","path":"title","type":"required"}}},"level":"error","message":"Error while adding  the todos Todo validation failed: title: Path `title` is required.","service":"user-service","stack":"ValidationError: Todo validation failed: title: Path `title` is required.\n    at model.Object.<anonymous>.Document.invalidate (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\mongoose\\lib\\document.js:3343:32)\n    at D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\mongoose\\lib\\document.js:3104:17\n    at D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\mongoose\\lib\\schemaType.js:1407:9\n    at processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-04-28T05:03:13.074Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:12:42.081Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:12:42.183Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:18:16.603Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:18:16.621Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:19:17.961Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:19:17.977Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:22:23.562Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:73:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)\n    at Object.worker (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\testWorker.js:106:12)","timestamp":"2025-04-28T05:22:23.581Z"}
